project:
  name: "HilliumOS Core"
  description: "Public MVP code repository (hillium-core)."
  root_path: "."

rules:
  - "EXECUTION ROOT: You are currently AT the project root."
  - "NO NESTING: All file operations must happen in the current directory ('.')."
  - "FORBIDDEN: DO NOT create a project subfolder (e.g. 'hilliumos/', 'hillium-core/')."
  - "DOCS: MVP docs and Work Packages live in /Users/jsaldana/GitLocalRepo/HilliumOS (read-only)."
  - "PRIVATE: Roadmap/internal docs live in /Users/jsaldana/GitLocalRepo/HilliumOS-Private (confidential)."
  - "ROOT GUARD: Do not cd outside this repo unless the user explicitly asks."

verification:
  repair_loop:
    enabled: true
    max_attempts: 3
    timeout_per_attempt_s: 120

# v10.7.90: Forge container integration
build:
  strategy: "auto"              # auto, forge, host
  container: "hillium-forge"    # Docker container name
  
  force_container_for:          # ALWAYS use container if available
    - "cargo"
    - "rustc"
    - "pytest"
    - "python3"
    - "python"
    - "pip"
    - "piper"
    - "espeak"
    - "which"                   # Verify binaries in container
  
  force_host_for:               # NEVER use container
    - "git"
    - "docker"
    - "make"
forge:
  setup:
    - "pip install -e loqus_core"
    - "pip install pytest pytest-asyncio"
    - "cargo build -p hipposerver -p hillium_backend"
  
  setup_cache_keys:
    - "loqus_core/pyproject.toml"
    - "Cargo.toml"
    - "Cargo.lock"
    - "hipposerver/Cargo.toml"
    - "hillium_backend/Cargo.toml"